# week03/example-1/docker-compose.yml

version: "3.9"
services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: product_db
    restart: always # Keep the database running
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Product Microservice (FastAPI)
  product_service:
    build: ./backend/product_service
    container_name: product_service_container
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy # Wait for the database to be healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 # Command to run the FastAPI app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app_container
    ports:
      - "3000:80"
    depends_on:
      product_service:
        condition: service_started
